### PR TITLE
Rename CRD f5ipam to ipam

### PR DESCRIPTION
**Pull request by agupta49**
**Description**:  Rename CRD f5ipam to ipam

**Changes Proposed in PR**:

**Fixes**: #_Github issue id_

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Review by subbuv26 — APPROVED** [review]
LGTM

**Review by vklohiya — APPROVED** [review]
Looks Fine

**Pull request merged**
